/*
 * 10_transport_network_graph.sql
 * Dedicated transportation signal property graph for Seer Transport network demos.
 */

SET SERVEROUTPUT ON
PROMPT Creating transportation signal network graph schema...

BEGIN
    EXECUTE IMMEDIATE 'DROP PROPERTY GRAPH transport_signal_network';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE NOT IN (-942, -4043) THEN
            DBMS_OUTPUT.PUT_LINE('Skipping transport_signal_network drop: ' || SQLERRM);
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transport_case_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transport_relationships CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transport_exception_cases CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transport_entities CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

CREATE TABLE transport_entities (
  entity_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  entity_key       VARCHAR2(64) NOT NULL UNIQUE,
  display_name     VARCHAR2(160) NOT NULL,
  entity_type      VARCHAR2(30) NOT NULL
                   CHECK (entity_type IN (
                     'shipper','carrier','broker','terminal','port',
                     'lane','equipment_pool','yard','case_anchor'
                   )),
  risk_score       NUMBER(5,2) DEFAULT 0 NOT NULL,
  risk_level       VARCHAR2(16) DEFAULT 'medium' NOT NULL
                   CHECK (risk_level IN ('critical','high','medium','low')),
  region           VARCHAR2(80),
  city             VARCHAR2(80),
  channel          VARCHAR2(32) DEFAULT 'operations' NOT NULL,
  service_value    NUMBER(14,2) DEFAULT 0 NOT NULL,
  event_count      NUMBER(8) DEFAULT 0 NOT NULL,
  first_seen       TIMESTAMP DEFAULT SYSTIMESTAMP,
  last_seen        TIMESTAMP DEFAULT SYSTIMESTAMP,
  is_active_risk   NUMBER(1) DEFAULT 0 NOT NULL
                   CHECK (is_active_risk IN (0, 1))
);

CREATE INDEX idx_transport_entities_type ON transport_entities(entity_type);
CREATE INDEX idx_transport_entities_risk ON transport_entities(risk_score DESC);
CREATE INDEX idx_transport_entities_channel ON transport_entities(channel);

CREATE TABLE transport_relationships (
  relationship_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  from_entity       NUMBER NOT NULL REFERENCES transport_entities(entity_id),
  to_entity         NUMBER NOT NULL REFERENCES transport_entities(entity_id),
  relationship_type VARCHAR2(40) NOT NULL
                    CHECK (relationship_type IN (
                      'serves_lane','shares_terminal','hands_off_to','brokers_for',
                      'capacity_depends_on','exception_linked_to','rerouted_through',
                      'uses_equipment_pool','port_constrained_by','escalates_to'
                    )),
  strength          NUMBER(4,3) DEFAULT 0.5 NOT NULL,
  event_count       NUMBER(8) DEFAULT 1 NOT NULL,
  service_value     NUMBER(14,2) DEFAULT 0 NOT NULL,
  first_seen        TIMESTAMP DEFAULT SYSTIMESTAMP,
  last_seen         TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT uq_transport_relationship UNIQUE (from_entity, to_entity, relationship_type)
);

CREATE INDEX idx_transport_rel_from ON transport_relationships(from_entity);
CREATE INDEX idx_transport_rel_to ON transport_relationships(to_entity);
CREATE INDEX idx_transport_rel_type ON transport_relationships(relationship_type);

CREATE TABLE transport_exception_cases (
  case_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  case_ref      VARCHAR2(64) NOT NULL UNIQUE,
  case_type     VARCHAR2(60) NOT NULL,
  status        VARCHAR2(30) DEFAULT 'investigating' NOT NULL
                CHECK (status IN ('investigating','escalated','monitoring','mitigated','closed')),
  risk_score    NUMBER(5,2) DEFAULT 0 NOT NULL,
  service_value_at_risk NUMBER(14,2) DEFAULT 0 NOT NULL,
  event_count   NUMBER(8) DEFAULT 0 NOT NULL,
  opened_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE transport_case_entities (
  case_entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  case_id        NUMBER NOT NULL REFERENCES transport_exception_cases(case_id),
  entity_id      NUMBER NOT NULL REFERENCES transport_entities(entity_id),
  role           VARCHAR2(40) NOT NULL
                 CHECK (role IN ('seed','shipper','carrier','terminal','lane','port','equipment','control_team')),
  evidence_score NUMBER(5,2) DEFAULT 0 NOT NULL,
  CONSTRAINT uq_transport_case_entity UNIQUE (case_id, entity_id, role)
);

CREATE INDEX idx_transport_case_entities_case ON transport_case_entities(case_id);
CREATE INDEX idx_transport_case_entities_entity ON transport_case_entities(entity_id);

CREATE PROPERTY GRAPH transport_signal_network
  VERTEX TABLES (
    transport_entities KEY (entity_id)
      LABEL entity
      PROPERTIES (
        entity_id,
        entity_key,
        display_name,
        entity_type,
        risk_score,
        risk_level,
        region,
        city,
        channel,
        service_value,
        event_count,
        is_active_risk
      ),
    transport_exception_cases KEY (case_id)
      LABEL exception_case
      PROPERTIES (
        case_id,
        case_ref,
        case_type,
        status,
        risk_score,
        service_value_at_risk,
        event_count
      )
  )
  EDGE TABLES (
    transport_relationships KEY (relationship_id)
      SOURCE KEY (from_entity) REFERENCES transport_entities (entity_id)
      DESTINATION KEY (to_entity) REFERENCES transport_entities (entity_id)
      LABEL related_to
      PROPERTIES (
        relationship_type,
        strength,
        event_count,
        service_value
      ),
    transport_case_entities KEY (case_entity_id)
      SOURCE KEY (case_id) REFERENCES transport_exception_cases (case_id)
      DESTINATION KEY (entity_id) REFERENCES transport_entities (entity_id)
      LABEL contains_entity
      PROPERTIES (
        role,
        evidence_score
      )
  );

COMMIT;

SELECT '10_transport_network_graph.sql complete - transportation signal graph schema ready.' AS status FROM dual;
