/*
 * 10_developer_ecosystem_graph.sql
 * Dedicated High Tech Product Signal Graph.
 * Keeps inherited influencer tables available while adding a finance-parity
 * domain graph for product portfolios, advocates, partners, buyers, blockers,
 * capacity centers, and signal cases.
 */
SET SERVEROUTPUT ON

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE tech_graph_entities (
      entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      entity_key VARCHAR2(80) NOT NULL UNIQUE,
      display_name VARCHAR2(180) NOT NULL,
      entity_type VARCHAR2(40) NOT NULL,
      influence_score NUMBER(5,2) DEFAULT 0 NOT NULL,
      urgency_score NUMBER(5,2) DEFAULT 0 NOT NULL,
      risk_level VARCHAR2(16) DEFAULT 'medium' NOT NULL,
      region VARCHAR2(80),
      city VARCHAR2(80),
      channel VARCHAR2(32),
      product_value NUMBER(14,2) DEFAULT 0 NOT NULL,
      signal_count NUMBER(8) DEFAULT 0 NOT NULL,
      is_priority NUMBER(1) DEFAULT 0 NOT NULL,
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT tech_graph_entity_type_ck CHECK (entity_type IN (
        'advocate', 'partner', 'portfolio', 'buyer', 'architecture',
        'blocker', 'capacity_center', 'signal_cluster', 'fab',
        'wafer_lot', 'process_step', 'yield_metric', 'bom_component',
        'supplier', 'supplier_site', 'eco', 'npi_milestone',
        'plm_record', 'osat_site', 'test_program', 'contract_manufacturer',
        'channel_inventory', 'distributor', 'warranty_cohort',
        'field_quality_incident', 'telemetry_signal', 'customer_commitment',
        'order_promise', 'service_case', 'firmware_release',
        'change_review_board', 'demand_forecast', 'allocation_plan',
        'capacity_reservation', 'design_ip', 'substrate_material',
        'manufacturing_route', 'quality_gate', 'support_operation',
        'lifecycle_stage'
      )),
      CONSTRAINT tech_graph_risk_ck CHECK (risk_level IN ('low', 'medium', 'high', 'critical'))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created tech_graph_entities.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('tech_graph_entities already exists.');
    ELSE
      RAISE;
    END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  FOR c IN (
    SELECT constraint_name
    FROM user_constraints
    WHERE table_name = 'TECH_GRAPH_ENTITIES'
      AND constraint_type = 'C'
      AND constraint_name = 'TECH_GRAPH_ENTITY_TYPE_CK'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE tech_graph_entities DROP CONSTRAINT ' ||
      DBMS_ASSERT.SIMPLE_SQL_NAME(c.constraint_name);
  END LOOP;

  SELECT COUNT(*) INTO v_exists
  FROM user_constraints
  WHERE table_name = 'TECH_GRAPH_ENTITIES'
    AND constraint_name = 'TECH_GRAPH_ENTITY_TYPE_CK';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE tech_graph_entities ADD CONSTRAINT tech_graph_entity_type_ck
      CHECK (entity_type IN (
        'advocate', 'partner', 'portfolio', 'buyer', 'architecture',
        'blocker', 'capacity_center', 'signal_cluster', 'fab',
        'wafer_lot', 'process_step', 'yield_metric', 'bom_component',
        'supplier', 'supplier_site', 'eco', 'npi_milestone',
        'plm_record', 'osat_site', 'test_program', 'contract_manufacturer',
        'channel_inventory', 'distributor', 'warranty_cohort',
        'field_quality_incident', 'telemetry_signal', 'customer_commitment',
        'order_promise', 'service_case', 'firmware_release',
        'change_review_board', 'demand_forecast', 'allocation_plan',
        'capacity_reservation', 'design_ip', 'substrate_material',
        'manufacturing_route', 'quality_gate', 'support_operation',
        'lifecycle_stage'
      ))
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE tech_graph_relationships (
      relationship_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      from_entity NUMBER NOT NULL REFERENCES tech_graph_entities(entity_id),
      to_entity NUMBER NOT NULL REFERENCES tech_graph_entities(entity_id),
      relationship_type VARCHAR2(48) NOT NULL,
      strength NUMBER(4,3) DEFAULT 0.5 NOT NULL,
      signal_count NUMBER(8) DEFAULT 1 NOT NULL,
      product_value NUMBER(14,2) DEFAULT 0 NOT NULL,
      evidence_text VARCHAR2(500),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT tech_graph_relationship_ck CHECK (relationship_type IN (
        'advocates_for', 'mentions_product', 'influences_buyer',
        'blocks_launch', 'depends_on_architecture', 'amplifies_signal',
        'partners_with', 'routes_to_capacity_center', 'mitigates_blocker',
        'supplied_by', 'constrained_by', 'manufactured_at', 'tested_by',
        'requires_component', 'changes_bom', 'delays_npi', 'impacts_yield',
        'blocks_commitment', 'creates_order_risk',
        'correlates_with_field_quality', 'triggers_warranty_exposure',
        'mitigated_by_eco', 'reallocated_to_channel',
        'requires_osat_capacity', 'feeds_order_promise',
        'consumes_wafer_starts', 'qualified_by_test_program',
        'governed_by_plm_record', 'releases_firmware_to',
        'routed_through_logistics', 'certified_by',
        'backed_by_capacity_reservation', 'escalates_service_case',
        'updates_allocation_plan', 'shares_design_ip',
        'monitored_by_telemetry', 'reviewed_by_crb',
        'drives_demand_forecast', 'splits_channel_supply',
        'passes_quality_gate', 'advances_lifecycle_stage'
      ))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created tech_graph_relationships.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('tech_graph_relationships already exists.');
    ELSE
      RAISE;
    END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  FOR c IN (
    SELECT constraint_name
    FROM user_constraints
    WHERE table_name = 'TECH_GRAPH_RELATIONSHIPS'
      AND constraint_type = 'C'
      AND constraint_name = 'TECH_GRAPH_RELATIONSHIP_CK'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE tech_graph_relationships DROP CONSTRAINT ' ||
      DBMS_ASSERT.SIMPLE_SQL_NAME(c.constraint_name);
  END LOOP;

  SELECT COUNT(*) INTO v_exists
  FROM user_constraints
  WHERE table_name = 'TECH_GRAPH_RELATIONSHIPS'
    AND constraint_name = 'TECH_GRAPH_RELATIONSHIP_CK';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE tech_graph_relationships ADD CONSTRAINT tech_graph_relationship_ck
      CHECK (relationship_type IN (
        'advocates_for', 'mentions_product', 'influences_buyer',
        'blocks_launch', 'depends_on_architecture', 'amplifies_signal',
        'partners_with', 'routes_to_capacity_center', 'mitigates_blocker',
        'supplied_by', 'constrained_by', 'manufactured_at', 'tested_by',
        'requires_component', 'changes_bom', 'delays_npi', 'impacts_yield',
        'blocks_commitment', 'creates_order_risk',
        'correlates_with_field_quality', 'triggers_warranty_exposure',
        'mitigated_by_eco', 'reallocated_to_channel',
        'requires_osat_capacity', 'feeds_order_promise',
        'consumes_wafer_starts', 'qualified_by_test_program',
        'governed_by_plm_record', 'releases_firmware_to',
        'routed_through_logistics', 'certified_by',
        'backed_by_capacity_reservation', 'escalates_service_case',
        'updates_allocation_plan', 'shares_design_ip',
        'monitored_by_telemetry', 'reviewed_by_crb',
        'drives_demand_forecast', 'splits_channel_supply',
        'passes_quality_gate', 'advances_lifecycle_stage'
      ))
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE product_signal_cases (
      case_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      case_ref VARCHAR2(80) NOT NULL UNIQUE,
      case_type VARCHAR2(80) NOT NULL,
      status VARCHAR2(30) DEFAULT 'investigating' NOT NULL,
      urgency_score NUMBER(5,2) DEFAULT 0 NOT NULL,
      product_value_at_risk NUMBER(14,2) DEFAULT 0 NOT NULL,
      signal_count NUMBER(8) DEFAULT 0 NOT NULL,
      executive_summary VARCHAR2(500),
      created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created product_signal_cases.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('product_signal_cases already exists.');
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE product_signal_case_entities (
      case_entity_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
      case_id NUMBER NOT NULL REFERENCES product_signal_cases(case_id),
      entity_id NUMBER NOT NULL REFERENCES tech_graph_entities(entity_id),
      role VARCHAR2(48) NOT NULL,
      evidence_score NUMBER(5,2) DEFAULT 0 NOT NULL,
      evidence_note VARCHAR2(400),
      CONSTRAINT product_signal_case_role_ck CHECK (role IN (
        'source_signal', 'impacted_product', 'developer_advocate',
        'buyer_account', 'launch_blocker', 'capacity_owner', 'mitigation_path',
        'bom_component', 'supplier_owner', 'fab_owner', 'quality_signal',
        'warranty_exposure', 'order_promise', 'eco_owner', 'plm_owner',
        'osat_owner', 'channel_owner', 'field_service_owner',
        'firmware_owner', 'demand_plan'
      ))
    )
  ]';
  DBMS_OUTPUT.PUT_LINE('Created product_signal_case_entities.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('product_signal_case_entities already exists.');
    ELSE
      RAISE;
    END IF;
END;
/

DECLARE
  v_exists NUMBER := 0;
BEGIN
  FOR c IN (
    SELECT constraint_name
    FROM user_constraints
    WHERE table_name = 'PRODUCT_SIGNAL_CASE_ENTITIES'
      AND constraint_type = 'C'
      AND constraint_name = 'PRODUCT_SIGNAL_CASE_ROLE_CK'
  ) LOOP
    EXECUTE IMMEDIATE 'ALTER TABLE product_signal_case_entities DROP CONSTRAINT ' ||
      DBMS_ASSERT.SIMPLE_SQL_NAME(c.constraint_name);
  END LOOP;

  SELECT COUNT(*) INTO v_exists
  FROM user_constraints
  WHERE table_name = 'PRODUCT_SIGNAL_CASE_ENTITIES'
    AND constraint_name = 'PRODUCT_SIGNAL_CASE_ROLE_CK';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE product_signal_case_entities ADD CONSTRAINT product_signal_case_role_ck
      CHECK (role IN (
        'source_signal', 'impacted_product', 'developer_advocate',
        'buyer_account', 'launch_blocker', 'capacity_owner', 'mitigation_path',
        'bom_component', 'supplier_owner', 'fab_owner', 'quality_signal',
        'warranty_exposure', 'order_promise', 'eco_owner', 'plm_owner',
        'osat_owner', 'channel_owner', 'field_service_owner',
        'firmware_owner', 'demand_plan'
      ))
    ]';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX tech_graph_entities_type_ix ON tech_graph_entities(entity_type, risk_level, urgency_score)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX tech_graph_rel_from_ix ON tech_graph_relationships(from_entity, relationship_type)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX tech_graph_rel_to_ix ON tech_graph_relationships(to_entity, relationship_type)';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE OR REPLACE VIEW developer_ecosystem_nodes_v AS
    SELECT
      entity_id AS advocate_id,
      entity_key AS advocate_key,
      display_name AS advocate_name,
      entity_type,
      CASE entity_type
        WHEN 'advocate' THEN 'Product Advocate'
        WHEN 'partner' THEN 'Partner Engineer'
        WHEN 'portfolio' THEN 'Product Portfolio'
        WHEN 'buyer' THEN 'Enterprise Buyer'
        WHEN 'architecture' THEN 'Reference Architecture'
        WHEN 'blocker' THEN 'Launch Blocker'
        WHEN 'capacity_center' THEN 'Availability Center'
        WHEN 'fab' THEN 'Semiconductor Fab'
        WHEN 'wafer_lot' THEN 'Wafer Lot'
        WHEN 'process_step' THEN 'Fab Process Step'
        WHEN 'yield_metric' THEN 'Yield Metric'
        WHEN 'bom_component' THEN 'BOM Component'
        WHEN 'supplier' THEN 'Supplier'
        WHEN 'supplier_site' THEN 'Supplier Site'
        WHEN 'eco' THEN 'Engineering Change Order'
        WHEN 'npi_milestone' THEN 'NPI Milestone'
        WHEN 'plm_record' THEN 'PLM Record'
        WHEN 'osat_site' THEN 'OSAT Site'
        WHEN 'test_program' THEN 'Test Program'
        WHEN 'contract_manufacturer' THEN 'Contract Manufacturer'
        WHEN 'channel_inventory' THEN 'Channel Inventory'
        WHEN 'distributor' THEN 'Distributor'
        WHEN 'warranty_cohort' THEN 'Warranty Cohort'
        WHEN 'field_quality_incident' THEN 'Field Quality Incident'
        WHEN 'telemetry_signal' THEN 'Connected Product Telemetry'
        WHEN 'customer_commitment' THEN 'Customer Commitment'
        WHEN 'order_promise' THEN 'Order Promise'
        WHEN 'service_case' THEN 'Service Case'
        WHEN 'firmware_release' THEN 'Firmware Release'
        WHEN 'change_review_board' THEN 'Change Review Board'
        WHEN 'demand_forecast' THEN 'Demand Forecast'
        WHEN 'allocation_plan' THEN 'Allocation Plan'
        WHEN 'capacity_reservation' THEN 'Capacity Reservation'
        WHEN 'design_ip' THEN 'Design IP'
        WHEN 'substrate_material' THEN 'Substrate Material'
        WHEN 'manufacturing_route' THEN 'Manufacturing Route'
        WHEN 'quality_gate' THEN 'Quality Gate'
        WHEN 'support_operation' THEN 'Support Operation'
        WHEN 'lifecycle_stage' THEN 'Lifecycle Stage'
        ELSE 'Signal Cluster'
      END AS entity_label,
      LOWER(REPLACE(entity_key, ' ', '_')) AS advocate_handle,
      channel AS source_channel,
      influence_score AS authority_score,
      urgency_score,
      risk_level,
      region,
      city,
      product_value,
      signal_count,
      is_priority
    FROM tech_graph_entities
  ]';
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE OR REPLACE VIEW developer_ecosystem_edges_v AS
    SELECT
      r.relationship_id,
      r.from_entity,
      r.to_entity,
      src.display_name AS from_name,
      dst.display_name AS to_name,
      r.relationship_type,
      r.strength,
      r.signal_count,
      r.product_value,
      r.evidence_text
    FROM tech_graph_relationships r
    JOIN tech_graph_entities src ON src.entity_id = r.from_entity
    JOIN tech_graph_entities dst ON dst.entity_id = r.to_entity
  ]';
END;
/

BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE PROPERTY GRAPH tech_product_signal_network
      VERTEX TABLES (
        tech_graph_entities KEY (entity_id) LABEL entity
          PROPERTIES (
            entity_id, entity_key, display_name, entity_type,
            influence_score, urgency_score, risk_level, region, city,
            channel, product_value, signal_count, is_priority,
            created_at, updated_at
          ),
        product_signal_cases KEY (case_id) LABEL signal_case
          PROPERTIES (
            case_id, case_ref, case_type, status, urgency_score,
            product_value_at_risk, signal_count, executive_summary,
            created_at, updated_at
          )
      )
      EDGE TABLES (
        tech_graph_relationships KEY (relationship_id)
          SOURCE KEY (from_entity) REFERENCES tech_graph_entities(entity_id)
          DESTINATION KEY (to_entity) REFERENCES tech_graph_entities(entity_id)
          LABEL related_to
          PROPERTIES (
            relationship_id, from_entity, to_entity, relationship_type,
            strength, signal_count, product_value, evidence_text, created_at
          ),
        product_signal_case_entities KEY (case_entity_id)
          SOURCE KEY (case_id) REFERENCES product_signal_cases(case_id)
          DESTINATION KEY (entity_id) REFERENCES tech_graph_entities(entity_id)
          LABEL contains_entity
          PROPERTIES (
            case_entity_id, case_id, entity_id, role,
            evidence_score, evidence_note
          )
      )
      OPTIONS (ENFORCED MODE)
  ]';
  DBMS_OUTPUT.PUT_LINE('Created property graph tech_product_signal_network.');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('tech_product_signal_network already exists.');
    ELSE
      RAISE;
    END IF;
END;
/

ALTER PROPERTY GRAPH tech_product_signal_network COMPILE;

COMMENT ON TABLE tech_graph_entities IS 'High Tech Product Signal Graph vertices: product advocates, partners, portfolios, customer commitments, design architectures, product lifecycle blockers, capacity centers, and signal clusters.';
COMMENT ON TABLE tech_graph_relationships IS 'High Tech Product Signal Graph edges connecting product signals, products, customer commitments, blockers, architectures, fabs, contract manufacturing, and capacity centers.';
COMMENT ON TABLE product_signal_cases IS 'High-tech signal cases that group urgent customer demand, supplier risk, BOM/ECO exposure, field quality, warranty analytics, blockers, and product value at risk.';
COMMENT ON TABLE product_signal_case_entities IS 'Membership table linking product signal cases to graph entities with a role and evidence score.';
